CREATE TABLE tb_food_items (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
foodCategory ENUM('VEGETAIS', 'FRIOS', 'LATICINIOS', 'CARNES', 'CEREAIS', 'FRUTAS', 'BEBIDAS', 'LEGUMES') NOT NULL,
quantidade INT NOT NULL,
validade DATE NOT NULL
)